# This is a basic workflow to help you get started with Actions

name: Data Processing Request

on:
  issues:
    types:
      - opened
      - edited
      - reopened
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v4.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: Show parsed data JSON
        env:
          parsed_data: ${{ steps.parse.outputs.payload }}
        run: |
          echo "$parsed_data"
          echo "Parsed data JSON:"
          echo "Job Name: $parsed_data" | jq .["Job Name"]

      